name: Test 
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Run Unit Test
      run: dotnet test
    - name: Build Solution
      run: dotnet build --configuration Release